[mysql]
host="192.168.1.8"
port=3306
user="loante"
password="12345678"
dbName="loante_db"

[http]
port=51111
debug=true
host="http://192.168.1.5:51111"

[safety]
secret="theconditionofbeingprotectedfromorunlikely"
expired=100000000

[maps]
TestMap={1 ="haha",2 ="hehe" }
ServiceDeductType={1="人民币",2 = "美金"}
ServiceType={1="短信",2="风控",3="服务费"}
SmsCompany={1 ="牛信"}
SmsTypes={1="验证码", 2="放款成功通知", 3="还款前一天提醒", 4="还款当天通知", 5="逾期天数通知", 6="全额还款完成发送提额短信", 7="其它"}
BlankTypes={1="身份证号", 2="手机号", 3="银行卡号", 4="姓名", 5="通讯手机号", 6="pan卡号"}
SystemSettingType={1="bool值", 2="数字", 3="普通字符串"}
StatisticsCompany={1="adjust"}
RiskModel={1="水星"}
MchFundType={1="现金充值",2="服务退款",3="现金退款",4="服务扣款",5="催收提醒短信扣款",6="风控服务费扣款"}
RepaymentWish={ 1 = "有能力有意愿还款",2 = "有能力无意愿还款", 3 = "无能力有意愿还款", 4 = "无意愿无能力还款", 5 = "其他"}
VisitTag={ 1="有人接听", 2="WhatsApp可联", 3="whatsAPP未回复", 4="无人接听", 5="电话占线", 6="关机", 7="其他方式可联", 8="没有whatsap账号", 9="空号错号", 10="停机", 11="特殊【中介黑产催收】", 12="其他"}
RepaymentRelationship={ 1="本人", 2="配偶", 3="父母", 4="子女", 5="亲人", 6="同事", 7="朋友", 8="其他"}
UTRStatus={ 1="待处理", 2="审核驳回", 3="已到账", 4="等待到账"}
